#!/bin/zsh

# General functions
tattach() {
    if (( $# == 0 )) then
       echo "Pass session name"
       return 1;
    fi
    tmux attach -t $1
}

spin() {
    # Check if tspin is available
    if ! command -v tspin &> /dev/null; then
        echo "Error: tspin command not found"
        return 1
    fi

    if (( $# == 0 )) then
       echo "At least one argument expected"
       return 1;
    fi

    "$@" 2>&1 | tspin
}

# Nuke current python env
nuke-venv() {
    echo "Nuking python env " $PYENV_VIRTUAL_ENV
    pip freeze | grep -v "^-e"  |  grep -v "#" | xargs pip uninstall -y
    echo "Editable projects need to be uninstalled by hand."
    pip list
}

start-agent() {
   eval "$(ssh-agent -s)" 
   ssh-add ~/.ssh/id_ed25519
}

install-py-packages-editable() {
   find . -type f -name "setup.cfg" -execdir pip install -e . --no-deps \;
}

