#!/bin/zsh

# General functions
tattach() {
    if (( $# == 0 )) then
       echo "Pass session name"
       return 1;
    fi
    tmux attach -t $1
}

spin() {
    # Check if tspin is available
    if ! command -v tspin &> /dev/null; then
        echo "Error: tspin command not found"
        return 1
    fi

    if (( $# == 0 )) then
       echo "At least one argument expected"
       return 1;
    fi

    "$@" 2>&1 | tspin
}


start-agent() {
   eval "$(ssh-agent -s)" 
   ssh-add ~/.ssh/id_ed25519
}

# yazi shortcut
if command -v yazi &> /dev/null; then
  function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d '' cwd < "$tmp"
    [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
    rm -f -- "$tmp"
  }
fi
